"""drop monthly stock table

Revision ID: 2d4681a0ac41
Revises: e76ae490f10b
Create Date: 2026-06-06 22:56:46.205323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d4681a0ac41'
down_revision: Union[str, Sequence[str], None] = 'e76ae490f10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('opening', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('inbound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('outbound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('closing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('stock_sku_id_fkey')),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('stock_upload_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_pkey')),
    sa.UniqueConstraint('sku_id', 'period', name=op.f('uq_stock_sku_period'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
