"""sku overrides

Revision ID: 809bb18a3f1a
Revises: 466728a0c882
Create Date: 2026-06-06 18:59:42.166258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809bb18a3f1a'
down_revision: Union[str, Sequence[str], None] = '466728a0c882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('overrides', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'overrides')
    # ### end Alembic commands ###
