"""sku raw 1c fields

Revision ID: c9421bce8f88
Revises: d57c9dd076a1
Create Date: 2026-06-05 13:42:57.026470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9421bce8f88'
down_revision: Union[str, Sequence[str], None] = 'd57c9dd076a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('group_kind', sa.String(length=100), nullable=True))
    op.add_column('skus', sa.Column('unit', sa.String(length=50), nullable=True))
    op.add_column('skus', sa.Column('boxes_per_layer', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('layers_per_pallet', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('units_per_box', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('units_per_pallet', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('temp', sa.String(length=50), nullable=True))
    op.add_column('skus', sa.Column('company', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'company')
    op.drop_column('skus', 'temp')
    op.drop_column('skus', 'units_per_pallet')
    op.drop_column('skus', 'units_per_box')
    op.drop_column('skus', 'layers_per_pallet')
    op.drop_column('skus', 'boxes_per_layer')
    op.drop_column('skus', 'unit')
    op.drop_column('skus', 'group_kind')
    # ### end Alembic commands ###
