"""sales table

Revision ID: dafa86bb6be3
Revises: c9421bce8f88
Create Date: 2026-06-06 17:54:42.192073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafa86bb6be3'
down_revision: Union[str, Sequence[str], None] = 'c9421bce8f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('gross_profit', sa.Float(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'period', name='uq_sales_sku_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
