"""stock_daily table

Revision ID: e76ae490f10b
Revises: 809bb18a3f1a
Create Date: 2026-06-06 21:03:24.024269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76ae490f10b'
down_revision: Union[str, Sequence[str], None] = '809bb18a3f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('opening', sa.Float(), nullable=False),
    sa.Column('inbound', sa.Float(), nullable=False),
    sa.Column('outbound', sa.Float(), nullable=False),
    sa.Column('closing', sa.Float(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'day', name='uq_stock_daily_sku_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_daily')
    # ### end Alembic commands ###
